# makefile
# Created by IBM WorkFrame/2 MakeMake at 20:44:59 on 2 Aug 1997
#
# The actions included in this make file are:
#  Compile::IPF Compiler

.SUFFIXES: .IPF .hlp 

.all: \
    E:\C_Projects\MG_Help_Source\mg.hlp

.IPF.hlp:
    @echo " Compile::IPF Compiler "
    ipfc.exe %s

E:\C_Projects\MG_Help_Source\mg.hlp: \
    E:\C_Projects\MG_Help_Source\mg.IPF
